version: '3'
services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: esports-haven
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "3306:3306"
    volumes:
      - "my-db:/var/lib/mysql"

  ###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: [ "1025", "1080" ]
  ###< symfony/mailer ###
volumes:
  my-db:
